### ISSUE TITLE
push -r azure: aiohttp error

### ISSUE THREAD

**Issue by piotlinski** [iterative/dvc-azure#30]
# Bug Report

## Description

With DVC 2.8.1, I am not able to push cache to remote storage at Azure Blob. I am getting `aiohttp`'s `ValueError`: `Cannot combine AUTHORIZATION header with AUTH argument or credentials encoded in URL` in either of the auth methods.

I tried authentication using username and `az login`, as well as access key.

### Reproduce

1. Install "dvc[all]" with python 3.9.7
2. Produce some cache
3. Log in with `az login`
4. Add azure remote storage
5. The error is there

### Expected

Cache gets pushed to the remote without error

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.8.1 (pip)
---------------------------------
Platform: Python 3.9.7 on Linux-5.14.12-arch1-1-x86_64-with-glibc2.33
Supports:
        azure (adlfs = 2021.9.1, knack = 0.8.2, azure-identity = 1.7.0),
        gdrive (pydrive2 = 1.10.0),
        gs (gcsfs = 2021.10.0),
        hdfs (fsspec = 2021.10.0, pyarrow = 5.0.0),
        webhdfs (fsspec = 2021.10.0),
        http (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.6),
        s3 (s3fs = 2021.10.0, boto3 = 1.17.106),
        ssh (sshfs = 2021.9.0),
        oss (ossfs = 2021.8.0),
        webdav (webdav4 = 0.9.3),
        webdavs (webdav4 = 0.9.3)
Cache types: symlink
Cache directory: ext4 on /dev/sdc1
Caches: local
Remotes: local, azure
Workspace directory: ext4 on /dev/nvme0n1p1
Repo: dvc, git
```

**Additional Information (if any):**

Here is the full stacktrace:
<details>
  <summary>Stacktrace</summary>

```
❯ dvc push -r azure -v
2021-10-20 12:05:28,463 DEBUG: Preparing to transfer data from ‚../../../storage/dvc' to 'azure://<link to container>'
2021-10-20 12:05:28,463 DEBUG: Preparing to collect status from 'azure://<link to container>'
2021-10-20 12:05:28,494 DEBUG: Collecting status from 'azure://<link to container>'
2021-10-20 12:05:28,495 DEBUG: Querying 2 hashes via object_exists
2021-10-20 12:05:28,517 ERROR: unexpected error - Cannot combine AUTHORIZATION header with AUTH argument or credentials encoded in URL
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/dvc/main.py", line 55, in main
    ret = cmd.do_run()
  File "/home/user/.local/lib/python3.9/site-packages/dvc/command/base.py", line 45, in do_run
    return self.run()
  File "/home/user/.local/lib/python3.9/site-packages/dvc/command/data_sync.py", line 57, in run
    processed_files_count = self.repo.push(
  File "/home/user/.local/lib/python3.9/site-packages/dvc/repo/__init__.py", line 50, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/user/.local/lib/python3.9/site-packages/dvc/repo/push.py", line 48, in push
    pushed += self.cloud.push(obj_ids, jobs, remote=remote, odb=odb)
  File "/home/user/.local/lib/python3.9/site-packages/dvc/data_cloud.py", line 85, in push
    return transfer(
  File "/home/user/.local/lib/python3.9/site-packages/dvc/objects/transfer.py", line 153, in transfer
    status = compare_status(src, dest, obj_ids, check_deleted=False, **kwargs)
  File "/home/user/.local/lib/python3.9/site-packages/dvc/objects/status.py", line 160, in compare_status
    dest_exists, dest_missing = status(
  File "/home/user/.local/lib/python3.9/site-packages/dvc/objects/status.py", line 122, in status
    exists = hashes.intersection(
  File "/home/user/.local/lib/python3.9/site-packages/dvc/objects/status.py", line 48, in _indexed_dir_hashes
    dir_exists.update(odb.list_hashes_exists(dir_hashes - dir_exists))
  File "/home/user/.local/lib/python3.9/site-packages/dvc/objects/db/base.py", line 415, in list_hashes_exists
    ret = list(itertools.compress(hashes, in_remote))
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 608, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/user/.local/lib/python3.9/site-packages/dvc/objects/db/base.py", line 406, in exists_with_progress
    ret = self.fs.exists(path_info)
  File "/home/user/.local/lib/python3.9/site-packages/dvc/fs/fsspec_wrapper.py", line 136, in exists
    return self.fs.exists(self._with_bucket(path_info))
  File "/home/user/.local/lib/python3.9/site-packages/adlfs/spec.py", line 1350, in exists
    return sync(self.loop, self._exists, path)
  File "/home/user/.local/lib/python3.9/site-packages/fsspec/asyn.py", line 71, in sync
    raise return_result
  File "/home/user/.local/lib/python3.9/site-packages/fsspec/asyn.py", line 25, in _runner
    result[0] = await coro
  File "/home/user/.local/lib/python3.9/site-packages/adlfs/spec.py", line 1372, in _exists
    if await bc.exists():
  File "/home/user/.local/lib/python3.9/site-packages/azure/core/tracing/decorator_async.py", line 74, in wrapper_use_tracer
    return await func(*args, **kwargs)
  File "/home/user/.local/lib/python3.9/site-packages/azure/storage/blob/aio/_blob_client_async.py", line 597, in exists
    await self._client.blob.get_properties(
  File "/home/user/.local/lib/python3.9/site-packages/azure/storage/blob/_generated/aio/operations/_blob_operations.py", line 394, in get_properties
    pipeline_response = await self._client._pipeline.run(request, stream=False, **kwargs)
  File "/home/user/.local/lib/python3.9/site-packages/azure/core/pipeline/_base_async.py", line 215, in run
    return await first_node.send(pipeline_request)
  File "/home/user/.local/lib/python3.9/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  File "/home/user/.local/lib/python3.9/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  File "/home/user/.local/lib/python3.9/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  [Previous line repeated 5 more times]
  File "/home/user/.local/lib/python3.9/site-packages/azure/core/pipeline/policies/_redirect_async.py", line 64, in send
    response = await self.next.send(request)
  File "/home/user/.local/lib/python3.9/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  File "/home/user/.local/lib/python3.9/site-packages/azure/storage/blob/_shared/policies_async.py", line 99, in send
    response = await self.next.send(request)
  File "/home/user/.local/lib/python3.9/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  File "/home/user/.local/lib/python3.9/site-packages/azure/storage/blob/_shared/policies_async.py", line 56, in send
    response = await self.next.send(request)
  File "/home/user/.local/lib/python3.9/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  File "/home/user/.local/lib/python3.9/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  File "/home/user/.local/lib/python3.9/site-packages/azure/core/pipeline/_base_async.py", line 116, in send
    await self._sender.send(request.http_request, **request.context.options),
  File "/home/user/.local/lib/python3.9/site-packages/azure/storage/blob/_shared/base_client_async.py", line 180, in send
    return await self._transport.send(request, **kwargs)
  File "/home/user/.local/lib/python3.9/site-packages/azure/core/pipeline/transport/_aiohttp.py", line 231, in send
    result = await self.session.request(    # type: ignore
  File "/home/user/.local/lib/python3.9/site-packages/aiohttp/client.py", line 468, in _request
    raise ValueError(
ValueError: Cannot combine AUTHORIZATION header with AUTH argument or credentials encoded in URL
------------------------------------------------------------
2021-10-20 12:05:28,949 DEBUG: Version info for developers:
DVC version: 2.8.1 (pip)
---------------------------------
Platform: Python 3.9.7 on Linux-5.14.12-arch1-1-x86_64-with-glibc2.33
Supports:
        azure (adlfs = 2021.9.1, knack = 0.8.2, azure-identity = 1.7.0),
        gdrive (pydrive2 = 1.10.0),
        gs (gcsfs = 2021.10.0),
        hdfs (fsspec = 2021.10.0, pyarrow = 5.0.0),
        webhdfs (fsspec = 2021.10.0),
        http (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.6),
        s3 (s3fs = 2021.10.0, boto3 = 1.17.106),
        ssh (sshfs = 2021.9.0),
        oss (ossfs = 2021.8.0),
        webdav (webdav4 = 0.9.3),
        webdavs (webdav4 = 0.9.3)
Cache types: symlink
Cache directory: ext4 on /dev/sdc1
Caches: local
Remotes: local, azure
Workspace directory: ext4 on /dev/nvme0n1p1
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2021-10-20 12:05:28,950 DEBUG: Analytics is enabled.
2021-10-20 12:05:29,039 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmprl9ltfue']'
2021-10-20 12:05:29,042 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmprl9ltfue']'
```
</details>

**Comment by dtrifiro** [comment]
Closing as stale. Feel free to reopen if it still is a problem
